name: 'Unity Action (XRTK)'
description: 'Runs Unity with the provided options'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  editor-path:
    description: 'Path to the Unity Editor'
    required: true
  project-path:
    description: 'Path to the Unity project'
    required: true
  build-target:
    description: 'Platform build target'
    required: false
  args:
    description: 'Unity cli arguments'
    required: false
    default: '-quit -batchmode'
  name:
    description: 'Name of the Unity Log'
    required: false
    default: 'Unity'
runs:
  using: "composite"
  steps:
    - name: '${{ inputs.name }}'
      run: ${{ github.action_path }}//unity-action.ps1 -editorPath "${{ inputs.editor-path }}" -projectPath "${{ inputs.project-path }}" -buildTarget ${{ inputs.build-target }} -additionalArgs "${{ inputs.args }}" -name ${{ inputs.name }}
      shell: pwsh
