name: 'Unity Action (XRTK)'
description: 'Runs Unity with the provided options'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  build-target:
    description: 'Platform build target'
    required: false
    default: ''
  args:
    description: 'Unity cli arguments'
    required: false
    default: '-quit -batchmode -nographics'
  log-name:
    description: 'Name of the Unity Log'
    required: false
    default: 'Unity'
runs:
  using: 'node16'
  main: 'dist/index.js'
