name: 'Unity Action (XRTK)'
description: 'Runs Unity with the provided options'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  editor-path:
    description: 'Path to the Unity Editor'
    required: true
  project-path:
    description: 'Path to the Unity project'
    required: true
  build-target:
    description: 'Platform build target'
    required: true
  args:
    description: 'Unity cli arguments'
    required: false
    default: '-quit -batchmode'
  name:
    description: 'Name of the Unity Action'
    required: false
    default: 'Unity'
runs:
  using: "composite"
  steps:
    - name: '${{ inputs.name }}'
      run: |
        $editorPath = "${{ inputs.editor-path }}"
        $projectPath = "${{ inputs.project-path }}"
        $bulidTarget = "${{ inputs.build-target }}"
        $additionalArgs = "${{ inputs.args }}".Trim()
        $name = "${{ inputs.name }}"
        $buildTargetArgs = ""

        if ( -not [string]::IsNullOrEmpty($bulidTarget) ) {
          $buildTargetArgs = "-buildTarget `"$bulidTarget`" "
        }

        $logDirectory = "$projectPath/Builds/Logs"

        if ( -not (Test-Path -Path $logDirectory)) {
          $logDirectory = New-Item -ItemType Directory -Force -Path $logDirectory | Select-Object
        }

        Write-Host "Log Directory: $logDirectory"

        $date = Get-Date -Format "yyyyMMddTHHmmss"
        $logName = "$logDirectory/$name-$date"
        $logPath = "$logName.log"

        if( $additionalArgs -like "*runEditorTests" ) {
          $testPath = "$logName.xml"
          $additionalArgs += " -editorTestsResultFile `"$testPath`""
        }

        $buildArgs = "$buildTargetArgs-projectPath `"$projectPath`" -logfile `"$logPath`" $additionalArgs"
        Write-Host "::group::$editorPath $buildArgs"

        $process = Start-Process -FilePath "$editorPath" -ArgumentList "$buildArgs" -PassThru

        $ljob = Start-Job -ScriptBlock {
          param($log)

          while ( -not (Test-Path $log -Type Leaf) ) {
              Start-Sleep -Milliseconds 1
          }

          Get-Content "$log" -Wait
        } -ArgumentList $logPath

        $processId = $process.Id

        while ( -not $process.HasExited )
        {
          # While waiting, Get-Content checks the file once each second
          Start-Sleep -Milliseconds 1
          Receive-Job $ljob

          if ( (Get-Process -Id $processId -ErrorAction SilentlyContinue) -eq $null )
          {
            Write-Host "Unity process has ended unexpectedly..."
            break
          }
        }

        Write-Host "Unity Process $processId Complete!"

        # Wait for the last of the log information to be written
        $fileLocked = $true

        do {
          try
          {
            $file = Convert-Path $logPath
            $fileStream = [System.IO.File]::Open($file,'Open','Write')
            $fileStream.Close()
            $fileStream.Dispose()
            $fileLocked = $false
          }
          catch
          {
            $fileLocked = $true
            Start-Sleep -Milliseconds 1
            Receive-Job $ljob
          }

          if ( $stopwatch.elapsed -lt $timeout )
          {
            if ( (-not $global:PSVersionTable.Platform) -or ($global:PSVersionTable.Platform -eq "Win32NT") ) {
              Write-Host "End of log stream, attempting to cleanup child processes..."
              Get-CimInstance Win32_Process | Where-Object { $_.ParentProcessId -eq $processId } | ForEach-Object { Stop-Process -Id $_.ProcessId -ErrorAction SilentlyContinue }
            } else {
              Write-Host "End of log stream"
            }
          }
        } while ( $fileLocked )

        Write-Host "Cleaning up jobs..."

        # Clean up job
        Receive-Job $ljob
        Stop-Job $ljob
        Remove-Job $ljob

        Write-Host "::endgroup::"

        exit $process.ExitCode
      shell: pwsh
