name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          #  build-target: StandaloneLinux64
          - os: windows
            build-target: StandaloneWindows64
          #- os: macos-latest
          #  build-target: StandaloneOSX

    steps:
      - name: checkout self
        uses: actions/checkout@v3

      - name: checkout test project
        uses: actions/checkout@v3
        with:
          repository: xrtk/com.xrtk.test
          path: test-project

      - run: npm install

      - uses: xrtk/unity-setup@v1
        with:
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'

      - uses: ./
        with:
          log-name: 'Test'
          args: '-quit -batchmode'
