name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UNITY_PROJECT_PATH: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2 # Use this if you're activating pro license with matrix
      matrix:
        include:
          - os: ubuntu-latest
            build-target: StandaloneLinux64
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: StandaloneOSX

    steps:
      - name: checkout self
        uses: actions/checkout@v4

      - run: npm install

      - name: checkout test project
        uses: actions/checkout@v4
        with:
          repository: xrtk/com.xrtk.test
          path: test-project

      - uses: xrtk/unity-setup@v7.4
        with:
          build-targets: ${{ matrix.build-target }}
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'

        # Activates the installation with the provided credentials
      - uses: xrtk/activate-unity-license@v5.1
        with:
          # Required
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
          # Optional
          license-type: 'Personal' # Chooses license type to use [ Personal, Professional ]
          # serial: ${{ secrets.UNITY_SERIAL }} # Required for pro/plus activations
          auth-key: ${{ secrets.UNITY_2FA_KEY }} # required for personal activations

      - name: xrtk/unity-action
        uses: ./
        with:
          log-name: 'Test'
          args: '-quit -batchmode -nographics'

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        if: always()
        with:
          name: '${{ github.run_number }}.${{ github.run_attempt }}-${{ runner.os }}-${{ matrix.build-target }}-Artifacts'
          path: |
            ${{ env.UNITY_PROJECT_PATH }}/**/*.log
            ${{ env.UNITY_PROJECT_PATH }}/Builds/${{ matrix.build-target }}/
